# Generated by Django 4.2.20 on 2025-03-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('applicant', models.CharField(max_length=255)),
                ('updated_date', models.DateField()),
                ('resume_file', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
