# Generated by Django 4.2.20 on 2025-03-24 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_resumes_delete_resume'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Resumes',
            new_name='Resume',
        ),
    ]
