# Generated by Django 4.2.20 on 2025-03-24 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0003_rename_resumes_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='issuing_organization',
            new_name='issued_by',
        ),
    ]
